AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cristiano-artifacts
      AccessControl: Private
Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
