name: Deploy API Upload

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1   

          - name: Empacotar código da Lambda e enviar para o S3
        run: 
          
          zip -r ../codigo-lambda.zip .
          
          aws s3 cp ../codigo-lambda.zip s3://SEU-BUCKET-DE-ARTIFACTS/codigo-lambda.zip

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/api-upload.yaml \
            --stack-name api-upload-stack \
            --capabilities CAPABILITY_NAMED_IAM