name: Deploy API Upload

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Empacotar código da Lambda
        run: |
          zip -r codigo-lambda.zip .

      - name: Enviar ZIP para bucket de artefatos
        run: |
          # Obtém o nome do bucket de artefatos criado pelo CloudFormation
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name api-upload-stack \
            --query "Stacks[0].Outputs[?OutputKey=='ArtifactBucketName'].OutputValue" \
            --output text)

          echo "Usando bucket de artefatos: $BUCKET_NAME"
          aws s3 cp codigo-lambda.zip s3://$BUCKET_NAME/lambda/upload.zip

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/api-upload.yaml \
            --stack-name api-upload-stack \
            --capabilities CAPABILITY_NAMED_IAM
